package kr.toxicity.model.standalone.resourcepack

data class ResourcePackSettings(
    val namespace: String = "bettermodel",
    val useObfuscation: Boolean = false,
    val description: String = "Generated by BetterModel standalone resourcepack library.",
    val packFormat: Int = 46,
    val supportedFormats: PackMeta.VersionRange = PackMeta.VersionRange(22, 99),
    val minFormat: PackMeta.PackVersion = PackMeta.PackVersion(22),
    val maxFormat: PackMeta.PackVersion = PackMeta.PackVersion(99),
    val includeLegacyOverlay: Boolean = true,
    val includeModernOverlay: Boolean = true,
)
